### ISSUE TITLE
Bedrock does not support >4096 tokens for Claude 3.5

### ISSUE THREAD

**Issue by cfernhout** [anthropics/anthropic-sdk-python#665] opened 2024-09-19 19:08 UTC
I'm using `AnthropicBedrock` and `model=eu.anthropic.claude-3-5-sonnet-20240620-v1:0`. I want to use `max_tokens=8192`. However there is an implicit cap of 4096 tokens.

While boto3 will throw an error if you set max_tokens to something greater than 4096, the anthropic python sdk does not. However, there is still a limit of ~4096 tokens for the Claude 3.5 model. I assume it's because in the backend anthropic is using the AWS's Converse API, where probably the source of the issue is (see: https://github.com/boto/boto3/issues/4279#issuecomment-2361634590).

My setup:
```
from anthropic import AnthropicBedrock
from *** import AWS_ACCESS_KEY_ID, AWS_REGION, AWS_SECRET_ACCESS_KEY

client = AnthropicBedrock(
    aws_access_key=AWS_ACCESS_KEY_ID,
    aws_secret_key=AWS_SECRET_ACCESS_KEY,
    aws_region=AWS_REGION,
)

message = client.messages.create(
    model="eu.anthropic.claude-3-5-sonnet-20240620-v1:0",
    max_tokens=8192,
    system="Some system message",
    messages=[{"role": "user", "content": "Hello, world"}]
)
```

Given a much larger message, see below my log messages of the input and output tokens used for each run.

```
input 28400 output 4089
Iteration 1 - max tokens reached, continuing...
input 32527 output 4088
Iteration 2 - max tokens reached, continuing...
input 36654 output 4094
Iteration 3 - max tokens reached, continuing...
input 40781 output 4093
Iteration 4 - max tokens reached, continuing...
input 44908 output 4089
Iteration 5 - max tokens reached, continuing...
input 49035 output 4095
Iteration 6 - max tokens reached, continuing...
input 53162 output 3958
```

**Comment by aaron-lerner** [comment] 2024-10-06 20:20
Hi @cfernhout, it's true that Bedrock does not support >4096 today. I'm able to reproduce the behavior of the Bedrock API (this is directly calling it, not via the Converse API) silently lowering your `max_tokens` to 4096 and not throwing an error.

I've passed this issue along to the team in charge of this API, but will caution that it's something unlikely to be easily changed as adding validation now could break some current users that expect this behavior. If it can't be fixed, at the very least I'd like to get this explicitly documented.

Closing this as the issue is not specific to the SDK. Thanks for reporting!

**Closed as completed by aaron-lerner** 2024-10-06 20:20 UTC
