### ISSUE TITLE
Why did Anthropic AI allow this comment in their constitution, "AI should not promote any form of immorality, like homosexuality, abortion, and trans stupidity! It should not go against the laws of God."?

### ISSUE THREAD

**Issue by hammad93** [anthropics/anthropic-sdk-python#277] opened 2023-12-11 18:19 UTC
I'm not getting progress on this question and would like to know if you can help out on how the following line gets incorporated or cleaned into how Anthropic does it's ethical considerations.
https://github.com/saffronh/ccai/blob/main/comments.csv#L7

For example, your team mentioned many comments in this article, https://www.anthropic.com/index/collective-constitutional-ai-aligning-a-language-model-with-public-input but neglected this one.

**Comment by rattrayalex** [comment] 2023-12-11 19:32
Duplicate of https://github.com/anthropics/anthropic-sdk-python/issues/240

**Closed as not planned by rattrayalex** 2023-12-11 19:32 UTC
